name: NS248
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - anyio=3.6.2=pyhd8ed1ab_0
  - appdirs=1.4.4=pyh9f0ad1d_0
  - appnope=0.1.3=pyhd8ed1ab_0
  - argon2-cffi=21.3.0=pyhd8ed1ab_0
  - argon2-cffi-bindings=21.2.0=py39h02fc5c5_3
  - astropy=5.2.1=py39h4d8bf0d_0
  - asttokens=2.2.1=pyhd8ed1ab_0
  - attrs=22.2.0=pyh71513ae_0
  - babel=2.11.0=pyhd8ed1ab_0
  - backcall=0.2.0=pyh9f0ad1d_0
  - backports=1.0=pyhd8ed1ab_3
  - backports.functools_lru_cache=1.6.4=pyhd8ed1ab_0
  - beautifulsoup4=4.11.1=pyha770c72_0
  - blas=1.0=openblas
  - bleach=5.0.1=pyhd8ed1ab_0
  - brotli=1.0.9=h1a8c8d9_8
  - brotli-bin=1.0.9=h1a8c8d9_8
  - brotlipy=0.7.0=py39h02fc5c5_1005
  - bzip2=1.0.8=h3422bc3_4
  - c-ares=1.25.0=h93a5062_0
  - ca-certificates=2024.2.2=hf0a4a13_0
  - cairo=1.16.0=h302bd0f_5
  - certifi=2024.2.2=pyhd8ed1ab_0
  - cffi=1.15.1=py39h7e6b969_3
  - charset-normalizer=2.1.1=pyhd8ed1ab_0
  - colorama=0.4.6=pyhd8ed1ab_0
  - comm=0.1.2=pyhd8ed1ab_0
  - contourpy=1.0.7=py39haaf3ac1_0
  - cryptography=39.0.0=py39he2a39a8_0
  - cycler=0.11.0=pyhd8ed1ab_0
  - debugpy=1.6.4=py39h23fbdae_0
  - decorator=5.1.1=pyhd8ed1ab_0
  - defusedxml=0.7.1=pyhd8ed1ab_0
  - eigen=3.4.0=hc021e02_0
  - entrypoints=0.4=pyhd8ed1ab_0
  - et_xmlfile=1.1.0=pyhd8ed1ab_0
  - executing=1.2.0=pyhd8ed1ab_0
  - expat=2.5.0=hb7217d7_1
  - ffmpeg=4.2.2=h04105a8_0
  - flit-core=3.8.0=pyhd8ed1ab_0
  - fontconfig=2.14.2=h82840c6_0
  - fonttools=4.38.0=py39h02fc5c5_1
  - freetype=2.12.1=hd633e50_1
  - gettext=0.21.1=h0186832_0
  - giflib=5.2.1=h1a8c8d9_3
  - glib=2.69.1=h514c7bf_2
  - glob2=0.7=py_0
  - gmp=6.2.1=hc377ac9_3
  - gnutls=3.6.15=h887c41c_0
  - graphite2=1.3.14=hc377ac9_1
  - gst-plugins-base=1.14.1=h313beb8_1
  - gstreamer=1.14.1=h80987f9_1
  - h5py=3.9.0=py39haafd478_0
  - harfbuzz=4.3.0=he9eebac_1
  - hdf5=1.12.1=nompi_hd9dbc9e_104
  - icu=68.2=hbdafb3b_0
  - idna=3.4=pyhd8ed1ab_0
  - imageio=2.33.1=pyh8c1a49c_0
  - imageio-ffmpeg=0.4.9=pyhd8ed1ab_0
  - importlib-metadata=6.0.0=pyha770c72_0
  - importlib_resources=5.10.2=pyhd8ed1ab_0
  - ipykernel=6.19.4=pyh736e0ef_0
  - ipython=8.8.0=pyhd1c38e8_0
  - ipython_genutils=0.2.0=py_1
  - jedi=0.18.2=pyhd8ed1ab_0
  - jinja2=3.1.2=pyhd8ed1ab_1
  - joblib=1.2.0=pyhd8ed1ab_0
  - jpeg=9e=he4db4b2_2
  - json5=0.9.5=pyh9f0ad1d_0
  - jsonschema=4.17.3=pyhd8ed1ab_0
  - jupyter_client=7.4.8=pyhd8ed1ab_0
  - jupyter_core=5.1.2=py39h2804cbe_0
  - jupyter_events=0.5.0=pyhd8ed1ab_1
  - jupyter_server=2.0.6=pyhd8ed1ab_0
  - jupyter_server_terminals=0.4.3=pyhd8ed1ab_0
  - jupyterlab=3.5.2=pyhd8ed1ab_0
  - jupyterlab_pygments=0.2.2=pyhd8ed1ab_0
  - jupyterlab_server=2.18.0=pyhd8ed1ab_0
  - kiwisolver=1.4.4=py39haaf3ac1_1
  - krb5=1.20.1=h69eda48_0
  - lame=3.100=h1a8c8d9_1003
  - lcms2=2.14=h481adae_1
  - lerc=4.0.0=h9a09cb3_0
  - libblas=3.9.0=16_osxarm64_openblas
  - libbrotlicommon=1.0.9=h1a8c8d9_8
  - libbrotlidec=1.0.9=h1a8c8d9_8
  - libbrotlienc=1.0.9=h1a8c8d9_8
  - libcblas=3.9.0=16_osxarm64_openblas
  - libclang=12.0.0=default_hc321e17_4
  - libcurl=7.88.1=h9049daf_1
  - libcxx=14.0.6=h2692d47_0
  - libdeflate=1.14=h1a8c8d9_0
  - libedit=3.1.20191231=hc8eb9b7_2
  - libev=4.33=h93a5062_2
  - libexpat=2.5.0=hb7217d7_1
  - libffi=3.4.2=h3422bc3_5
  - libgfortran=5.0.0=11_3_0_hd922786_27
  - libgfortran5=11.3.0=hdaf2cc0_27
  - libiconv=1.17=h0d3ecfb_2
  - libidn2=2.3.4=h1a8c8d9_0
  - libjpeg-turbo=2.1.4=h1a8c8d9_0
  - liblapack=3.9.0=16_osxarm64_openblas
  - libllvm12=12.0.1=h93073aa_2
  - libnghttp2=1.57.0=h62f6fdd_0
  - libopenblas=0.3.21=openmp_hc731615_3
  - libopencv=4.6.0=hca03da5_5
  - libopus=1.3.1=h27ca646_1
  - libpng=1.6.39=h76d750c_0
  - libpq=12.15=h02f6b3c_1
  - libsodium=1.0.18=h27ca646_1
  - libsqlite=3.40.0=h76d750c_0
  - libssh2=1.11.0=h7a5bd25_0
  - libtasn1=4.19.0=h1a8c8d9_0
  - libtiff=4.5.0=heb92581_0
  - libunistring=0.9.10=h3422bc3_0
  - libvpx=1.10.0=hc377ac9_0
  - libwebp=1.2.4=ha3663a8_1
  - libwebp-base=1.2.4=h57fd34a_0
  - libxcb=1.13=h9b22ae9_1004
  - libxml2=2.10.4=h372ba2a_0
  - libxslt=1.1.37=habca612_0
  - libzlib=1.2.13=h03a7124_4
  - llvm-openmp=15.0.7=h7cfbb63_0
  - lxml=4.9.3=py39h50ffb84_0
  - markupsafe=2.1.1=py39h02fc5c5_2
  - matplotlib=3.6.2=py39hdf13c20_0
  - matplotlib-base=3.6.2=py39h35e9e80_0
  - matplotlib-inline=0.1.6=pyhd8ed1ab_0
  - mistune=2.0.4=pyhd8ed1ab_0
  - moviepy=1.0.3=pyhd8ed1ab_1
  - munkres=1.1.4=pyh9f0ad1d_0
  - nbclassic=0.4.8=pyhd8ed1ab_0
  - nbclient=0.7.2=pyhd8ed1ab_0
  - nbconvert=7.2.7=pyhd8ed1ab_0
  - nbconvert-core=7.2.7=pyhd8ed1ab_0
  - nbconvert-pandoc=7.2.7=pyhd8ed1ab_0
  - nbformat=5.7.1=pyhd8ed1ab_0
  - ncurses=6.4=h463b476_2
  - nest-asyncio=1.5.6=pyhd8ed1ab_0
  - nettle=3.7.3=h84b5d62_1
  - niondata=15.6.2=pyhd8ed1ab_0
  - nionswift=16.10.0=pyhd8ed1ab_0
  - nionswift-instrumentation=22.1.1=pyhd8ed1ab_0
  - nionswift-io=15.2.1=pyhd8ed1ab_0
  - nionswift-video-capture=2.6.0=pyhd8ed1ab_0
  - nionui=7.0.2=pyhd8ed1ab_0
  - nionutils=0.4.10=pyhd8ed1ab_0
  - notebook=6.5.2=pyha770c72_1
  - notebook-shim=0.2.2=pyhd8ed1ab_0
  - nspr=4.35=hb7217d7_0
  - nss=3.89.1=h313beb8_0
  - numpy=1.26.3=py39h3b2db8e_0
  - numpy-base=1.26.3=py39ha9811e2_0
  - opencv=4.6.0=py39hc90a7da_5
  - openh264=1.8.0=h98b2900_0
  - openjpeg=2.5.0=hbc2ba62_2
  - openpyxl=3.1.2=py39h0f82c59_0
  - openssl=3.3.0=h0d3ecfb_0
  - packaging=22.0=pyhd8ed1ab_0
  - pandas=1.5.2=py39hde7b980_2
  - pandoc=2.19.2=hce30654_1
  - pandocfilters=1.5.0=pyhd8ed1ab_0
  - parso=0.8.3=pyhd8ed1ab_0
  - patsy=0.5.3=pyhd8ed1ab_0
  - pcre=8.45=hbdafb3b_0
  - pexpect=4.8.0=pyh1a96a4e_2
  - pickleshare=0.7.5=py_1003
  - pillow=9.4.0=py39h8bbe137_0
  - pip=22.3.1=pyhd8ed1ab_0
  - pixman=0.40.0=h1a28f6b_0
  - pkgutil-resolve-name=1.3.10=pyhd8ed1ab_0
  - platformdirs=2.6.2=pyhd8ed1ab_0
  - pooch=1.6.0=pyhd8ed1ab_0
  - proglog=0.1.9=py_0
  - prometheus_client=0.15.0=pyhd8ed1ab_0
  - prompt-toolkit=3.0.36=pyha770c72_0
  - psutil=5.9.4=py39h02fc5c5_0
  - pthread-stubs=0.4=h27ca646_1001
  - ptyprocess=0.7.0=pyhd3deb0d_0
  - pure_eval=0.2.2=pyhd8ed1ab_0
  - py-opencv=4.6.0=hca03da5_5
  - pycparser=2.21=pyhd8ed1ab_0
  - pyerfa=2.0.0.1=py39h4d8bf0d_3
  - pygments=2.14.0=pyhd8ed1ab_0
  - pyopenssl=23.0.0=pyhd8ed1ab_0
  - pyparsing=3.0.9=pyhd8ed1ab_0
  - pyrsistent=0.19.3=py39h02fc5c5_0
  - pysocks=1.7.1=pyha2e5f31_6
  - python=3.9.15=hea58f1e_0_cpython
  - python-dateutil=2.8.2=pyhd8ed1ab_0
  - python-fastjsonschema=2.16.2=pyhd8ed1ab_0
  - python-json-logger=2.0.4=pyhd8ed1ab_0
  - python_abi=3.9=3_cp39
  - pytz=2022.7=pyhd8ed1ab_0
  - pyyaml=6.0=py39h02fc5c5_5
  - pyzmq=24.0.1=py39h0553236_1
  - qt-main=5.15.2=ha2d02b5_7
  - qt-webengine=5.15.9=h2903aaf_7
  - qtwebkit=5.212=h19f419d_5
  - readline=8.1.2=h46ed386_0
  - requests=2.28.1=pyhd8ed1ab_1
  - scikit-learn=1.2.1=py39h57c6424_0
  - scipy=1.10.0=py39h18313fe_0
  - seaborn=0.13.1=hd8ed1ab_0
  - seaborn-base=0.13.1=pyhd8ed1ab_0
  - send2trash=1.8.0=pyhd8ed1ab_0
  - setuptools=65.6.3=pyhd8ed1ab_0
  - six=1.16.0=pyh6c4a22f_0
  - sklearn-pandas=2.2.0=pyhd8ed1ab_0
  - sniffio=1.3.0=pyhd8ed1ab_0
  - soupsieve=2.3.2.post1=pyhd8ed1ab_0
  - sqlite=3.41.2=h80987f9_0
  - stack_data=0.6.2=pyhd8ed1ab_0
  - statsmodels=0.13.5=py39h4d8bf0d_2
  - terminado=0.17.1=pyhd1c38e8_0
  - threadpoolctl=3.1.0=pyh8a188c0_0
  - tinycss2=1.2.1=pyhd8ed1ab_0
  - tk=8.6.12=he1e0b03_0
  - tomli=2.0.1=pyhd8ed1ab_0
  - tornado=6.2=py39h02fc5c5_1
  - tqdm=4.66.1=pyhd8ed1ab_0
  - traitlets=5.8.0=pyhd8ed1ab_0
  - types-openpyxl=3.1.0.32=pyhd8ed1ab_0
  - typing-extensions=4.4.0=hd8ed1ab_0
  - typing_extensions=4.4.0=pyha770c72_0
  - tzdata=2022g=h191b570_0
  - tzlocal=5.2=py39h2804cbe_0
  - unicodedata2=15.0.0=py39h02fc5c5_0
  - urllib3=1.26.13=pyhd8ed1ab_0
  - wcwidth=0.2.5=pyh9f0ad1d_2
  - webencodings=0.5.1=py_1
  - websocket-client=1.4.2=pyhd8ed1ab_0
  - wheel=0.38.4=pyhd8ed1ab_0
  - x264=1!152.20180806=h1a28f6b_0
  - xorg-libxau=1.0.9=h27ca646_0
  - xorg-libxdmcp=1.1.3=h27ca646_0
  - xz=5.4.5=h80987f9_0
  - yaml=0.2.5=h3422bc3_2
  - zeromq=4.3.4=hbdafb3b_1
  - zipp=3.11.0=pyhd8ed1ab_0
  - zlib=1.2.13=h03a7124_4
  - zstd=1.5.2=h8128057_4
prefix: /Users/joshsteighner/opt/anaconda3/envs/NS248
